# Generated by Django 5.2.11 on 2026-02-19 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('physical_activity', models.CharField(choices=[('none', 'No Physical Activity'), ('light', 'Light(Walking occasionally)'), ('moderate', 'Moderate (Exercise 3x/week)'), ('heavy', 'Heavy (Daily intense exercise)')], max_length=20)),
                ('diet_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_veg', 'Non Vegetarian'), ('mixed', 'Mixed')], max_length=20)),
                ('smoking', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('sleep_hours', models.IntegerField()),
                ('frequent_thirst', models.BooleanField(default=False)),
                ('frequent_urination', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('blurred_vision', models.BooleanField(default=False)),
                ('chest_pain', models.BooleanField(default=False)),
                ('shortness_of_breath', models.BooleanField(default=False)),
                ('numbness_in_feet', models.BooleanField(default=False)),
                ('family_diabetes', models.BooleanField(default=False)),
                ('family_hypertension', models.BooleanField(default=False)),
                ('family_heart_disease', models.BooleanField(default=False)),
                ('family_kidney_disease', models.BooleanField(default=False)),
                ('already_diabetic', models.BooleanField(default=False)),
                ('already_hypertensive', models.BooleanField(default=False)),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='patients.healthprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RiskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.IntegerField()),
                ('diabetes_risk', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('hypertension_risk', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('heart_risk', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('refer_for_test', models.BooleanField(default=False)),
                ('recommendation', models.TextField()),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='patients.questionnaire')),
            ],
        ),
    ]
