# Generated by Django 5.2.11 on 2026-02-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskreport',
            name='reviewed_by_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
