# Generated by Django 5.2.11 on 2026-02-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_riskreport_reviewed_by_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskreport',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
