# Generated by Django 5.2.11 on 2026-03-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Protocol', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('bmi_obese_weight', models.IntegerField(default=20, help_text='Weight for BMI >= 35')),
                ('bmi_overweight_high', models.IntegerField(default=15, help_text='Weight for BMI >= 30')),
                ('bmi_overweight_low', models.IntegerField(default=10, help_text='Weight for BMI >= 25')),
                ('age_elderly_weight', models.IntegerField(default=15, help_text='Weight for Age >= 60')),
                ('age_senior_weight', models.IntegerField(default=10, help_text='Weight for Age >= 45')),
                ('age_middle_weight', models.IntegerField(default=5, help_text='Weight for Age >= 35')),
                ('smoking_weight', models.IntegerField(default=10)),
                ('alcohol_weight', models.IntegerField(default=5)),
                ('inactivity_weight', models.IntegerField(default=10)),
                ('light_activity_weight', models.IntegerField(default=5)),
                ('sleep_deprivation_weight', models.IntegerField(default=5)),
                ('symptom_weight', models.IntegerField(default=5, help_text='Weight per symptom reported')),
                ('family_history_weight', models.IntegerField(default=5, help_text='Weight per family condition')),
                ('diabetes_existing_weight', models.IntegerField(default=10)),
                ('hypertension_existing_weight', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Risk Configuration',
                'verbose_name_plural': 'Risk Configurations',
            },
        ),
    ]
