# Generated by Django 5.2.11 on 2026-04-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_riskconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskreport',
            name='ml_probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
